merlin::ijgp Class Reference
#include <ijgp.h>
Classes
struct sPair
Helper class for pairs of sorted indices.
Public Types
typedef graphical_model::findex findex
Factor index.
typedef graphical_model::vindex vindex
Variable index.
typedef graphical_model::flist flist
Collection of factor indices.
Public Member Functions
ijgp ()
Default constructor.
ijgp (const graphical_model &gm)
Constructor.
virtual ijgp * clone () const
Clone the model.
double ub () const
Upper bound on the optimal value.
double lb () const
Lower bound on the optimal value.
std::vector< size_t > best_config () const
Best configuration.
double logZ () const
Log value of the partition function.
double logZub () const
Upper bound on the log partition function.
double logZlb () const
Lower bound on the log partition function.
const factor & belief (size_t f) const
Belief associated with a node of the graph.
const factor & belief (variable v) const
Belief associated with a particular variable.
const factor & belief (variable_set vs) const
Belief associated with a set of variables.
const std::vector< factor > & beliefs () const
Beliefs associated with the variables.
const graphical_model & get_gm_orig () const
Access the original graphical model.
void write (const char *filename, const std::map< size_t, size_t > &evidence, const std::map< size_t, size_t > &old2new, const graphical_model &orig)
Write the solution to the output file.
virtual void run ()
Run the algorithm.
MER_ENUM (Task, MAR, MAP)
Inference tasks supported.
MER_ENUM (Property, iBound, Order, Iter, Task)
Properties of the algorithm.
MER_ENUM (ElimOp, Max, Sum)
Elimination operators (sum, max).
void set_ibound (size_t i)
Set the i-bound parameter.
size_t get_ibound () const
Return the i-bound parameter.
void set_order (const variable_order_t &ord)
Set the variable elimination order.
void set_order_method (OrderMethod method)
Set the variable elimination order method.
const variable_order_t & get_order ()
Return the variable elimination order.
const std::vector< vindex > & get_pseudo_tree ()
Return the pseudo tree.
void set_pseudo_tree (const vector< vindex > &p)
Set the pseudo tree.
void set_graphical_model (const graphical_model &gm)
Set the graphical model content.
void set_graphical_model (const vector< factor > &fs)
Set the graphical model content from a list of factors.
virtual void set_properties (std::string opt=std::string())
Set the properties of the algorithm.
factor elim (const factor &F, const variable_set &vs)
Eliminate a set of variables from a factor.
factor marg (const factor &F, const variable_set &vs)
Compute the marginal over a set of variables.
double score (const vector< variable_set > &fin, const variable &VX, size_t i, size_t j)
Scoring function for bucket aggregation.
void init ()
Create the mini-bucket based join-graph (symbols only).
factor _belief (findex a)
Compute the belief of a cluster.
factor _belief (findex a, size_t b)
Compute the belief of a cluster excluding an incoming message.
void forward ()
Forward (top-down) message passing.
void backward ()
Backward (bottom-up) message passing.
void update ()
Update the beliefs (marginals or max-marginals) for each variable.
void propagate (size_t nIter, double stopTime=-1, double stopObj=-1)
Iterative message passing over the join graph.
Protected Attributes
graphical_model m_gmo
Original graphical model.
size_t num_iter
Number of iterations.
Task m_task
Inference task.
ElimOp m_elim_op
Elimination operator.
size_t m_ibound
i-bound parameter
double m_log_z
Log partition function value.
variable_order_t m_order
Variable elimination order.
OrderMethod m_order_method
Ordering method.
std::vector< vindex > m_parents
Pseudo tree.
std::vector< factor > m_beliefs
Marginals (or beliefs)
std::vector< size_t > m_best_config
MAP assignment.
double m_lb
Lower bound (ie, value of the MAP assignment)
Additional Inherited Members
Detailed Description
Iterative Join-Graph Propagation (IJGP)
Based on [Dechter and Mateescu, 2002] and [Marinescu, Kask and Dechter, 2003]
Tasks supported: MAR and MAP
IJGP is parameterized by an i-bound which limits the size of each cluster in the join-graph to at most i distict variables. Clearly IJGP(1) is equivalent with Loopy Belief Propagation, while IJGP(w*) is equivalent with the Join-Tree algorithm, hence exact.
The join-graph used by IJGP is obtained by running the mini-bucket algorithm schematically (ie, without computing the actual messages, only their scopes) and then connecting the mini-buckets residing in the same bucket. Messages are then propagated along the join-graph edges, following a top-down or bottom-up schedule.
Note that IJGP is only used for MAR (sum-prod) and MAP (max-prod) tasks. It doesn't compute an upper-bound (on the partition function, or the MAP value) because of overcounting. Therefore, logZ reported during the execution of the algorithm shouldn't be used as a valid measure for bounding (ignore). For valid bounding, use the WMB algorithm implemented in this library.
Definition at line 44 of file ijgp.h.
Member Function Documentation
factor merlin::ijgp::_belief (findex a) [inline]
Compute the belief of a cluster.
Parameters
a The index of the cluster
Returns
the factor representing the belief of the cluster.
Definition at line 685 of file ijgp.h.
References merlin::graphical_model::m_factors.
Referenced by backward(), forward(), and update().
factor merlin::ijgp::_belief (findex a, size_t b) [inline]
Compute the belief of a cluster excluding an incoming message.
Parameters
a The index of the cluster to compute the belief of
b The index of the cluster sending the incoming message
Returns
the factor representing the belief of cluster a excluding the incoming message from b to a.
Definition at line 715 of file ijgp.h.
References merlin::graphical_model::m_factors.
const factor& merlin::ijgp::belief (size_t i) const [inline], [virtual]
Belief associated with a node of the graph.
Returns
the belief associated with a node of the graph. Nodes correspond typically to variables. The belied is a function represented by the Factor class.
Parameters
i The index of the node in the graph (from 0)
Implements merlin::algorithm.
Definition at line 98 of file ijgp.h.
References m_beliefs.
Referenced by run(), and write().
const factor& merlin::ijgp::belief (variable v) const [inline], [virtual]
Belief associated with a particular variable.
Parameters
v The variable to compute the belief of
Returns
the belief associated with a particular variable in the graphical model. The belief is a function represented by the Factor class.
Implements merlin::algorithm.
Definition at line 101 of file ijgp.h.
References m_beliefs.
const factor& merlin::ijgp::belief (variable_set vs) const [inline], [virtual]
Belief associated with a set of variables.
Parameters
vs The set of variables to compute the belief of
Returns
the belief associated with a set of variables in the graphical model. The belief is a function represented by the Factor class.
Implements merlin::algorithm.
Definition at line 104 of file ijgp.h.
const std::vector<factor>& merlin::ijgp::beliefs () const [inline], [virtual]
Beliefs associated with the variables.
Returns
the beliefs associated with the variables in the graphical model (one belief for each of the variables). The output vector is indexed by the same indexes used for the variables.
Implements merlin::algorithm.
Definition at line 107 of file ijgp.h.
References m_beliefs.
std::vector<size_t> merlin::ijgp::best_config () const [inline], [virtual]
Best configuration.
Returns
a vector containing the best configuration of the variables (i.e., variable value assignments) found so far. It is specific to optimization tasks (e.g., MAP, Marginal MAP).
Implements merlin::algorithm.
Definition at line 84 of file ijgp.h.
References m_best_config.
virtual ijgp* merlin::ijgp::clone () const [inline], [virtual]
Clone the model.
Returns
the pointer to the object containing the cloned model.
Implements merlin::algorithm.
Definition at line 71 of file ijgp.h.
References ijgp().
factor merlin::ijgp::elim (const factor & F, const variable_set & vs) [inline]
Eliminate a set of variables from a factor.
Parameters
F The reference of the factor to eliminate from
vs The set of variables to be eliminated
Returns
the factor resulted from eliminating the set of variables.
Definition at line 379 of file ijgp.h.
References merlin::factor::max(), and merlin::factor::sum().
Referenced by backward(), and forward().
void merlin::ijgp::init () [inline], [virtual]
Create the mini-bucket based join-graph (symbols only).
end for: variable elim order ///////////////////////////////////////
Implements merlin::algorithm.
Definition at line 452 of file ijgp.h.
References merlin::graph::add_edge(), merlin::graphical_model::add_factor(), merlin::set< T >::begin(), merlin::graph::edges(), merlin::set< T >::end(), merlin::graphical_model::erase(), merlin::graphical_model::get_factor(), merlin::graphical_model::get_factors(), merlin::graphical_model::induced_width(), merlin::graphical_model::insert(), merlin::graphical_model::m_factors, merlin::algorithm::m_start_time, merlin::graphical_model::num_factors(), merlin::graphical_model::nvar(), merlin::graphical_model::order(), merlin::graphical_model::pseudo_tree(), score(), merlin::graphical_model::var(), and merlin::graphical_model::with_variable().
Referenced by run().
double merlin::ijgp::lb () const [inline], [virtual]
Lower bound on the optimal value.
Returns
a lower bound on the optimal value defined by the inference task if available.
Implements merlin::algorithm.
Definition at line 81 of file ijgp.h.
double merlin::ijgp::logZ () const [inline], [virtual]
Log value of the partition function.
Returns
an estimate the log parition function. If the inference algorithm is an exact one then the return value is the exact log value of the partition function.
Implements merlin::algorithm.
Definition at line 88 of file ijgp.h.
References m_log_z.
double merlin::ijgp::logZlb () const [inline], [virtual]
Lower bound on the log partition function.
Returns
a lower bound on the log value of the parition function.
Implements merlin::algorithm.
Definition at line 94 of file ijgp.h.
References m_log_z.
double merlin::ijgp::logZub () const [inline], [virtual]
Upper bound on the log partition function.
Returns
an upper bound on the log value of the parition function. Most inference algorithms implemented in merlin support upper bounds on the log partition function.
Implements merlin::algorithm.
Definition at line 91 of file ijgp.h.
References m_log_z.
factor merlin::ijgp::marg (const factor & F, const variable_set & vs) [inline]
Compute the marginal over a set of variables.
Parameters
F The reference of the factor to marginalize over
vs The set of variables representing the scope of the marginal
Returns
the factor representing the marginal over the set of variables.
Definition at line 397 of file ijgp.h.
References merlin::factor::marginal(), and merlin::factor::maxmarginal().
Referenced by update().
void merlin::ijgp::propagate (size_t nIter, double stopTime = -1, double stopObj = -1) [inline]
Iterative message passing over the join graph.
Parameters
nIter The number of iterations
stopTime The time limit
stopObj The error tolerance (ie, difference between objective values)
Definition at line 855 of file ijgp.h.
References backward(), forward(), m_log_z, merlin::algorithm::m_start_time, and update().
Referenced by run().
virtual void merlin::ijgp::run () [inline], [virtual]
Run the algorithm.
Solves a probabilistic inference task.
Implements merlin::algorithm.
Definition at line 176 of file ijgp.h.
References belief(), init(), merlin::graphical_model::logP(), m_beliefs, m_best_config, m_gmo, m_lb, merlin::algorithm::m_start_time, m_task, num_iter, merlin::graphical_model::nvar(), propagate(), merlin::variable::states(), and merlin::graphical_model::var().
Referenced by Merlin::run().
double merlin::ijgp::score (const vector< variable_set > & fin, const variable & VX, size_t i, size_t j) [inline]
Scoring function for bucket aggregation.
Parameters
fin The set of factor scopes containing the pair (i,j) to be aggregated
VX The bucket variable
i The index of first scope
j The index of the second pair
Returns
the score that corresponds to aggregating the two scopes. It returns -3 if unable to combine, -1 for scope only aggregation, and otherwise a positive double score.
Definition at line 420 of file ijgp.h.
References merlin::variable_set::nvar().
Referenced by init().
void merlin::ijgp::set_graphical_model (const graphical_model & gm) [inline]
Set the graphical model content.
Parameters
gm The reference to the graphical model object
Definition at line 326 of file ijgp.h.
void merlin::ijgp::set_graphical_model (const vector< factor > & fs) [inline]
Set the graphical model content from a list of factors.
Parameters
fs The list of factors
Definition at line 334 of file ijgp.h.
References merlin::graphical_model::graphical_model().
void merlin::ijgp::set_ibound (size_t i) [inline]
Set the i-bound parameter.
Parameters
i The value of the i-bound (> 1)
Definition at line 272 of file ijgp.h.
Referenced by set_properties().
void merlin::ijgp::set_order (const variable_order_t & ord) [inline]
Set the variable elimination order.
Parameters
ord The variable order
Definition at line 287 of file ijgp.h.
void merlin::ijgp::set_order_method (OrderMethod method) [inline]
Set the variable elimination order method.
Parameters
method The elimination order method
Definition at line 295 of file ijgp.h.
virtual void merlin::ijgp::set_properties (std::string opt = std::string()) [inline], [virtual]
Set the properties of the algorithm.
Parameters
opt The string containing comma separated property value pairs
Definition at line 342 of file ijgp.h.
References set_ibound().
Referenced by ijgp(), and Merlin::run().
void merlin::ijgp::set_pseudo_tree (const vector< vindex > & p) [inline]
Set the pseudo tree.
Parameters
p The vector representing the pseudo tree
Definition at line 318 of file ijgp.h.
double merlin::ijgp::ub () const [inline], [virtual]
Upper bound on the optimal value.
Returns
an upper bound on the optimal value defined by the inference task. It is specific to optimization tasks such as MAP and Marginal MAP inference.
Implements merlin::algorithm.
Definition at line 78 of file ijgp.h.
void merlin::ijgp::write (const char * filename, const std::map< size_t, size_t > & evidence, const std::map< size_t, size_t > & old2new, const graphical_model & orig) [inline]
Write the solution to the output file.
Parameters
filename The output file name
evidence The evidence variable value pairs
old2new The mapping between old and new variable indexing
orig The graphical model prior to asserting evidence
Definition at line 125 of file ijgp.h.
References belief(), m_best_config, m_task, merlin::graphical_model::nvar(), merlin::variable::states(), and merlin::graphical_model::var().
Referenced by Merlin::run().
The documentation for this class was generated from the following file:
include/ijgp.h