merlin::factor_graph Class Reference
A factor graph base class.
#include <factor_graph.h>
Classes
class abstract_queue
Queue type wrapper.
class abstract_queue_fifo
Queue type for breadth-first search.
class abstract_queue_lifo
Stack type for depth-first search.
Public Types
typedef graphical_model::findex findex
Factor index.
typedef graphical_model::vindex vindex
Variable index.
typedef graphical_model::flist flist
Collection of factor indices.
Public Member Functions
factor_graph ()
Default constructor.
factor_graph (const factor_graph &fg)
Copy constructor.
factor_graph (std::vector< merlin::factor > fs)
Constructor.
template<class InputIterator >
factor_graph (InputIterator first, InputIterator last)
Constructor.
virtual factor_graph * clone ()
Clone the factor graph.
findex add_factor (const merlin::factor &F)
Add a new factor to the graphical model.
void remove_factor (findex f)
Remove a factor from the model.
findex local_factor (vindex i) const
Retrieve the factor index corresponding to a variable node.
findex local_factor (variable v) const
Retrieve the factor index corresponding to a variable node.
bool is_var_node (findex i) const
Check if a factor is a variable node in the factor graph.
flist adjacent_factors (variable v) const
Retrieve the factors adjacent to a variable node in the factor graph.
flist adjacent_factors (vindex v) const
Retrieve the factors adjacent to a variable node in the factor graph.
variable_set adjacent_vars (findex f) const
Retrieve the variables adjacent to a factor in the factor graph.
void swap (factor_graph &gm)
Swap the contents of two factor graphs.
MER_ENUM (TreeType, WidthFirst, DepthFirst, MaxWeight)
Type of tree.
std::vector< edge_t > span_tree (TreeType tt, variable root)
Create a spanning tree of the factor graph.
std::vector< edge_t > span_tree (TreeType tt=TreeType::WidthFirst)
Create a spanning tree of the factor graph rooted by a randomly selected variable.
Protected Types
typedef size_t eindex
Edge index.
Protected Member Functions
flist _neighbors (findex i) const
Retrieve the neighbors of a factor.
void check_factors ()
Check the factors for consistency (internal use only).
eindex _eindex (findex i, findex j)
Retrieve the index of the edge between two nodes.
Protected Attributes
std::vector< size_t > m_vindex
Factors representing variable nodes in factor graph.
Additional Inherited Members
Detailed Description
A factor graph base class.
A graphical model represented as a bipartite graph between variable nodes, corresponding to the variables, and factor nodes, corresponding to the factors. Internally, factors and variables are mainly referenced by integer indices, with 0 <= f < nFactors() and 0 <= v < nvar(). However, many interface functions are called using a variable object, Var(label,dim). To convert, var(v) gives the vth Var object and the internal function _vindex(V) gives the index corresponding to variable object V.
Definition at line 30 of file factor_graph.h.
Constructor & Destructor Documentation
merlin::factor_graph::factor_graph (const factor_graph & fg) [inline]
Copy constructor.
Parameters
fg The factor graph to be copied
Definition at line 52 of file factor_graph.h.
merlin::factor_graph::factor_graph (std::vector< merlin::factor > fs) [inline]
Constructor.
Parameters
fs The list of factors
Definition at line 60 of file factor_graph.h.
References check_factors(), m_vindex, and merlin::graphical_model::nvar().
template<class InputIterator > merlin::factor_graph::factor_graph (InputIterator first, InputIterator last) [inline]
Constructor.
Parameters
first The begin iterator of the factors list
last The end iterator of the factors list
Definition at line 72 of file factor_graph.h.
References check_factors(), m_vindex, and merlin::graphical_model::nvar().
Member Function Documentation
eindex merlin::factor_graph::_eindex (findex i, findex j) [inline], [protected]
Retrieve the index of the edge between two nodes.
Parameters
i The (factor) index of the head
j The (factor) index of the tail
Returns
the index of the edge between the two factors.
Definition at line 236 of file factor_graph.h.
References merlin::graph::edge(), and merlin::edge_id::idx.
flist merlin::factor_graph::_neighbors (findex i) const [inline], [protected]
Retrieve the neighbors of a factor.
Parameters
i The index of the factor
Returns
the list of factor indexes that are connected to the input factor.
Definition at line 194 of file factor_graph.h.
References merlin::graph::neighbors().
Referenced by adjacent_factors().
findex merlin::factor_graph::add_factor (const merlin::factor & F) [inline]
Add a new factor to the graphical model.
Parameters
F The factor to be added
Returns
the index of the newly added factor.
Definition at line 92 of file factor_graph.h.
References merlin::graph::add_edge(), merlin::graphical_model::add_factor(), merlin::variable_set::begin(), merlin::variable_set::end(), local_factor(), m_vindex, merlin::factor::nvar(), merlin::graphical_model::nvar(), and merlin::factor::vars().
Referenced by check_factors().
flist merlin::factor_graph::adjacent_factors (variable v) const [inline]
Retrieve the factors adjacent to a variable node in the factor graph.
Parameters
v The index of the variable
Returns
the list of factor indexes corresponding to the adjacent factors.
Definition at line 157 of file factor_graph.h.
References _neighbors(), and local_factor().
flist merlin::factor_graph::adjacent_factors (vindex v) const [inline]
Retrieve the factors adjacent to a variable node in the factor graph.
Parameters
v The index of the variable
Returns
the list of factor indexes corresponding to the adjacent factors.
Definition at line 166 of file factor_graph.h.
References _neighbors(), and local_factor().
variable_set merlin::factor_graph::adjacent_vars (findex f) const [inline]
Retrieve the variables adjacent to a factor in the factor graph.
Parameters
f The index of the factor
Returns
the list of variable indexes corresponding to the adjacent variables.
Definition at line 175 of file factor_graph.h.
References merlin::graphical_model::get_factor(), and merlin::factor::vars().
Referenced by merlin::lbp::obj_entropy().
virtual factor_graph* merlin::factor_graph::clone () [inline], [virtual]
Clone the factor graph.
Returns
a pointer to the cloned factor graph.
Reimplemented from merlin::graphical_model.
Definition at line 82 of file factor_graph.h.
References factor_graph().
bool merlin::factor_graph::is_var_node (findex i) const [inline]
Check if a factor is a variable node in the factor graph.
Parameters
i The index of the factor
Returns
true if the factor corresponds to a variable node, and false otherwise.
Definition at line 147 of file factor_graph.h.
References merlin::graphical_model::get_factor(), local_factor(), and merlin::graphical_model::nvar().
Referenced by check_factors(), merlin::lbp::obj_entropy(), and span_tree().
findex merlin::factor_graph::local_factor (vindex i) const [inline]
Retrieve the factor index corresponding to a variable node.
Parameters
i The index of a variable
Returns
the index of the factor associated with the variable in the factor graph.
Definition at line 127 of file factor_graph.h.
References m_vindex.
Referenced by add_factor(), adjacent_factors(), merlin::lbp::belief(), check_factors(), is_var_node(), remove_factor(), and span_tree().
findex merlin::factor_graph::local_factor (variable v) const [inline]
Retrieve the factor index corresponding to a variable node.
Parameters
v The index of a variable
Returns
the index of the factor associated with the variable in the factor graph.
Definition at line 137 of file factor_graph.h.
References merlin::graphical_model::_vindex(), and m_vindex.
void merlin::factor_graph::remove_factor (findex f) [inline]
Remove a factor from the model.
Parameters
f The index of the factor to be removed
Definition at line 111 of file factor_graph.h.
References merlin::graphical_model::_vindex(), merlin::variable_set::begin(), merlin::variable_set::end(), local_factor(), merlin::graphical_model::m_factors, m_vindex, merlin::graph::remove_edge(), and merlin::graphical_model::remove_factor().
std::vector<edge_t> merlin::factor_graph::span_tree (TreeType tt, variable root) [inline]
Create a spanning tree of the factor graph.
Parameters
tt The type of spanning tree
root The root (variable index) of the spanning tree
Returns
the spanning tree as a list of edge indexes in the factor graph.
Definition at line 311 of file factor_graph.h.
References merlin::graphical_model::_vindex(), merlin::set< T >::begin(), merlin::variable_set::begin(), merlin::set< T >::end(), merlin::variable_set::end(), merlin::graphical_model::get_factor(), is_var_node(), local_factor(), merlin::graph::neighbors(), merlin::graphical_model::num_factors(), merlin::graphical_model::nvar(), and merlin::factor::vars().
Referenced by span_tree().
std::vector<edge_t> merlin::factor_graph::span_tree (TreeType tt = TreeType::WidthFirst) [inline]
Create a spanning tree of the factor graph rooted by a randomly selected variable.
Parameters
tt The type of spanning tree
Returns
the spanning tree as a list of edge indexes in the factor graph.
Definition at line 375 of file factor_graph.h.
References merlin::graphical_model::nvar(), span_tree(), and merlin::graphical_model::var().
void merlin::factor_graph::swap (factor_graph & gm)
Swap the contents of two factor graphs.
Parameters
gm The factor graph to swap with
The documentation for this class was generated from the following file:
include/factor_graph.h