merlin::jglp Class Reference
#include <jglp.h>
Classes
struct sPair
Helper class for pairs of sorted indices.
Public Types
typedef graphical_model::findex findex
Factor index.
typedef graphical_model::vindex vindex
Variable index.
typedef graphical_model::flist flist
Collection of factor indices.
typedef flist::const_iterator flistIt
Iterator for collection of factor indeces.
Public Member Functions
jglp ()
Default constructor.
jglp (const graphical_model &gm)
Constructor.
virtual jglp * clone () const
Clone the algorithm.
double ub () const
Upper bound on the optimal value.
double lb () const
Lower bound on the optimal value.
std::vector< index > best_config () const
Best configuration.
double logZ () const
Log value of the partition function.
double logZub () const
Upper bound on the log partition function.
double logZlb () const
Lower bound on the log partition function.
const factor & belief (size_t f) const
Belief associated with a node of the graph.
const factor & belief (variable v) const
Belief associated with a particular variable.
const factor & belief (variable_set vs) const
Belief associated with a set of variables.
const std::vector< factor > & beliefs () const
Beliefs associated with the variables.
const graphical_model & get_gm_orig () const
Return the original graphical model.
MER_ENUM (Property, iBound, Order, Iter)
Properties of the algorithm.
void set_ibound (size_t i)
Set the i-bound parameter.
size_t get_ibound () const
Return the i-bound parameter.
void set_order (const variable_order_t &ord)
Set the variable elimination order.
void set_order_method (OrderMethod method)
Set the variable elimination order method.
const variable_order_t & get_order ()
Return the variable elimination order.
const std::vector< vindex > & get_pseudo_tree ()
Return the pseudo tree.
void set_pseudo_tree (const std::vector< vindex > &p)
Set the pseudo tree.
void set_graphical_model (const graphical_model &gm)
Set the graphical model content.
void set_graphical_model (const std::vector< factor > &fs)
Set the graphical model content from a list of factors.
virtual void set_properties (std::string opt=std::string())
Set the properties of the algorithm.
factor elim (const factor &F, const variable_set &vs)
Eliminate a set of variables from a factor.
factor marg (const factor &F, const variable_set &vs)
Compute the marginal over a set of variables.
double score (const std::vector< factor > &fin, const variable &VX, size_t i, size_t j)
Scoring function for bucket aggregation.
void init ()
Initialize the JGLP algorithm.
void tighten (size_t nIter, double stopTime=-1, double stopObj=-1)
Join graph propagation for tightening the bound.
void write (const char *filename, const std::map< size_t, size_t > &evidence, const std::map< size_t, size_t > &old2new, const graphical_model &orig)
Write the solution to the output file.
void run ()
Run the algorithm.
std::vector< index > config ()
Return the MAP configuration following the propagation.
Protected Attributes
graphical_model m_gmo
Original graphical model.
OrderMethod m_order_method
Variable ordering heuristic.
size_t m_ibound
Mini-bucket i-bound.
double m_log_z
Log partition function.
double m_lb
Lower bound.
variable_order_t m_order
Elimination ordering.
std::vector< vindex > m_parents
Pseudo tree.
std::vector< index > m_best_config
MAP assignment.
size_t m_num_iter
Number of iterations.
std::vector< flist > m_mini_buckets
Mini-buucket partitionings.
Additional Inherited Members
Detailed Description
Join-Graph Linear Programming (ie, Weighted mini-buckets for MAP inference)
Tasks supported: MAP
JGLP is a specialization of the weighted mini-bucket algorithm to the MAP inference task. It builds a join graph by running the mini-bucket algorithm schemetically, and then it connects the mini-buckets residing in the same bucket. JGLP shifts costs along the edges of the join graph by matching the max marginals of any two clusters connected by an edge. In practice, the algorithm typically tightens the MAP upper bound, however this is not a guarantee. It keeps track of the tightest upper bound found and its corresponding assignment.
Definition at line 36 of file jglp.h.
Member Function Documentation
const factor& merlin::jglp::belief (size_t i) const [inline], [virtual]
Belief associated with a node of the graph.
Returns
the belief associated with a node of the graph. Nodes correspond typically to variables. The belied is a function represented by the Factor class.
Parameters
i The index of the node in the graph (from 0)
Implements merlin::algorithm.
Definition at line 91 of file jglp.h.
const factor& merlin::jglp::belief (variable v) const [inline], [virtual]
Belief associated with a particular variable.
Parameters
v The variable to compute the belief of
Returns
the belief associated with a particular variable in the graphical model. The belief is a function represented by the Factor class.
Implements merlin::algorithm.
Definition at line 95 of file jglp.h.
const factor& merlin::jglp::belief (variable_set vs) const [inline], [virtual]
Belief associated with a set of variables.
Parameters
vs The set of variables to compute the belief of
Returns
the belief associated with a set of variables in the graphical model. The belief is a function represented by the Factor class.
Implements merlin::algorithm.
Definition at line 99 of file jglp.h.
const std::vector<factor>& merlin::jglp::beliefs () const [inline], [virtual]
Beliefs associated with the variables.
Returns
the beliefs associated with the variables in the graphical model (one belief for each of the variables). The output vector is indexed by the same indexes used for the variables.
Implements merlin::algorithm.
Definition at line 103 of file jglp.h.
std::vector<index> merlin::jglp::best_config () const [inline], [virtual]
Best configuration.
Returns
a vector containing the best configuration of the variables (i.e., variable value assignments) found so far. It is specific to optimization tasks (e.g., MAP, Marginal MAP).
Implements merlin::algorithm.
Definition at line 77 of file jglp.h.
References m_best_config.
virtual jglp* merlin::jglp::clone () const [inline], [virtual]
Clone the algorithm.
Returns
the pointer to the object containing the cloned algorithm.
Implements merlin::algorithm.
Definition at line 66 of file jglp.h.
References jglp().
factor merlin::jglp::elim (const factor & F, const variable_set & vs) [inline]
Eliminate a set of variables from a factor.
Parameters
F The reference of the factor to eliminate from
vs The set of variables to be eliminated
Returns
the factor resulted from eliminating the set of variables.
Definition at line 243 of file jglp.h.
References merlin::factor::max().
Referenced by run().
double merlin::jglp::lb () const [inline], [virtual]
Lower bound on the optimal value.
Returns
a lower bound on the optimal value defined by the inference task if available.
Implements merlin::algorithm.
Definition at line 74 of file jglp.h.
References m_lb.
double merlin::jglp::logZ () const [inline], [virtual]
Log value of the partition function.
Returns
an estimate the log parition function. If the inference algorithm is an exact one then the return value is the exact log value of the partition function.
Implements merlin::algorithm.
Definition at line 81 of file jglp.h.
References m_log_z.
double merlin::jglp::logZlb () const [inline], [virtual]
Lower bound on the log partition function.
Returns
a lower bound on the log value of the parition function.
Implements merlin::algorithm.
Definition at line 87 of file jglp.h.
References m_log_z.
double merlin::jglp::logZub () const [inline], [virtual]
Upper bound on the log partition function.
Returns
an upper bound on the log value of the parition function. Most inference algorithms implemented in merlin support upper bounds on the log partition function.
Implements merlin::algorithm.
Definition at line 84 of file jglp.h.
References m_log_z.
factor merlin::jglp::marg (const factor & F, const variable_set & vs) [inline]
Compute the marginal over a set of variables.
Parameters
F The reference of the factor to marginalize over
vs The set of variables representing the scope of the marginal
Returns
the factor representing the marginal over the set of variables.
Definition at line 253 of file jglp.h.
References merlin::factor::maxmarginal().
Referenced by run().
void merlin::jglp::run () [inline], [virtual]
Run the algorithm.
Solves a probabilistic inference task. end for: variable elim order
Implements merlin::algorithm.
Definition at line 451 of file jglp.h.
References merlin::graph::add_edge(), merlin::graphical_model::add_factor(), merlin::set< T >::begin(), elim(), merlin::set< T >::end(), merlin::factor::exp(), merlin::graphical_model::get_factors(), init(), merlin::graphical_model::insert(), merlin::factor::log(), merlin::graphical_model::logP(), merlin::graphical_model::m_factors, m_log_z, marg(), merlin::factor::max(), merlin::graphical_model::num_factors(), merlin::factor::nvar(), merlin::graphical_model::nvar(), merlin::set< T >::size(), tighten(), merlin::graphical_model::var(), and merlin::graphical_model::with_variable().
Referenced by Merlin::run().
double merlin::jglp::score (const std::vector< factor > & fin, const variable & VX, size_t i, size_t j) [inline]
Scoring function for bucket aggregation.
Parameters
fin The set of factor scopes containing the pair (i,j) to be aggregated
VX The bucket variable
i The index of first scope
j The index of the second pair
Returns
the score that corresponds to aggregating the two scopes. It returns -3 if unable to combine, -1 for scope only aggregation, and otherwise a positive double score.
Definition at line 268 of file jglp.h.
References merlin::factor::nvar(), and merlin::factor::vars().
void merlin::jglp::set_graphical_model (const graphical_model & gm) [inline]
Set the graphical model content.
Parameters
gm The reference to the graphical model object
Definition at line 195 of file jglp.h.
void merlin::jglp::set_graphical_model (const std::vector< factor > & fs) [inline]
Set the graphical model content from a list of factors.
Parameters
fs The list of factors
Definition at line 203 of file jglp.h.
References merlin::graphical_model::graphical_model().
void merlin::jglp::set_ibound (size_t i) [inline]
Set the i-bound parameter.
Parameters
i The value of the i-bound (> 1)
Definition at line 141 of file jglp.h.
Referenced by set_properties().
void merlin::jglp::set_order (const variable_order_t & ord) [inline]
Set the variable elimination order.
Parameters
ord The variable order
Definition at line 156 of file jglp.h.
void merlin::jglp::set_order_method (OrderMethod method) [inline]
Set the variable elimination order method.
Parameters
method The elimination order method
Definition at line 164 of file jglp.h.
virtual void merlin::jglp::set_properties (std::string opt = std::string()) [inline], [virtual]
Set the properties of the algorithm.
Parameters
opt The string containing comma separated property value pairs
Definition at line 211 of file jglp.h.
References set_ibound().
Referenced by jglp(), and Merlin::run().
void merlin::jglp::set_pseudo_tree (const std::vector< vindex > & p) [inline]
Set the pseudo tree.
Parameters
p The vector representing the pseudo tree
Definition at line 187 of file jglp.h.
void merlin::jglp::tighten (size_t nIter, double stopTime = -1, double stopObj = -1) [inline]
Join graph propagation for tightening the bound.
Parameters
nIter The number of iterations
stopTime The time limit
stopObj The difference between two successive objective values
Definition at line 347 of file jglp.h.
References config(), merlin::graph::edges(), merlin::graphical_model::m_factors, m_log_z, merlin::algorithm::m_start_time, and merlin::graphical_model::num_factors().
Referenced by run().
double merlin::jglp::ub () const [inline], [virtual]
Upper bound on the optimal value.
Returns
an upper bound on the optimal value defined by the inference task. It is specific to optimization tasks such as MAP and Marginal MAP inference.
Implements merlin::algorithm.
Definition at line 71 of file jglp.h.
References m_log_z.
void merlin::jglp::write (const char * filename, const std::map< size_t, size_t > & evidence, const std::map< size_t, size_t > & old2new, const graphical_model & orig) [inline]
Write the solution to the output file.
Parameters
filename The output file name
evidence The evidence variable value pairs
old2new The mapping between old and new variable indexing
orig The graphical model prior to asserting evidence
Definition at line 428 of file jglp.h.
References merlin::graphical_model::nvar().
Referenced by Merlin::run().
The documentation for this class was generated from the following file:
include/jglp.h